name: 'myproject'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    command: -p 1221
    expose:
      - 1221